version: "3"

services:
    frontend:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.dev
        command: yarn start
        volumes:
            - ..:/app
        ports:
            - 8080:8080
