version: "3"

services:
    frontend:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile.prod
        volumes:
            - ..:/app
        ports:
            - 8080:80
