version: "3.3"
services:
    frontend:
        build:
            context: ../frontend
            dockerfile: ../docker/Dockerfile.frontend
        command: yarn start
        volumes:
            - ../frontend:/app
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.dev
        command: npm start
        volumes:
            - ..:/app
