version: "3.3"
services:
    app:
        ports:
            - ${PORT}:${PORT}
    mongodb:
        image: mongo
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    mongo-express:
        image: mongo-express
        ports:
            - ${ME_PORT}:${ME_PORT}
        environment:
            ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
volumes:
    db_data:
