version: '3'
services:
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.dev
        command: yarn all
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        volumes:
            - ..:/app
