FROM node:14-alpine

WORKDIR /app

# Bundle app source
COPY . /app/

# install packages
RUN yarn global add react-scripts
RUN yarn install --production

# Build React app
WORKDIR /app/frontend
RUN yarn install --production
RUN yarn build

# Go back to app root
WORKDIR /app

# copy react build files
RUN mv /app/frontend/build/* /app/public
RUN node /app/docker/deploy.js
RUN rm .env
