version: "3.3"
services:
    mongodb:
        restart: always
    mongo-express:
        restart: always
    app:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.prod
        command: npm run prod
        restart: always
